name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'master'
      - 'release/*'
    tags:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.daemon=false"

jobs:
  jvm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 21

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Test
        run: |
          ./gradlew -Dtest.java.version=${{ matrix.java-version }} build --stacktrace
          

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'robeden/log-indexer' && startsWith(github.ref, 'refs/tags/') }}
    needs: [jvm]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Upload Artifacts
        run: |
          ./gradlew clean publish --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ARTIFACT_SIGNING_PASSWORD }}
